* Foreword
#+BEGIN_QUOTE
Though I do not pretend, by this little treatise, to make any person a perfect master of Country-dancing, yet, with the help of these my instructions, and their taking some opportunities of going into company, and by the assistance of a good partner, begin with some easy dances, by which any one, having a good ear to music, may very soon become a proficient.

—A. D. Dancing Master
#+END_QUOTE

This is neither a period book nor a scholarly one—for the first, turn to one of the many treatises by 18th-century dancing masters; for the second, academia already has you covered.

Instead, this is intended as a crash course to get late 18th- and early 19th-century reenactors with minimal country dancing experience prepared for a Saturday evening dance. Its first goal is to be practical; a secondary goal is to be historically-defensible. Anyone who claims to do truly historically /correct/ dancing is lying: sources are simply too scarce, and those that exist are too open to interpretation.  What follows is the result of my time with a few dance treatises, more than a few books of dance music, various other written primary sources, and dozens of country dances as a dancer, as a musician, as a dancing master, as the least-experienced person in the room by an order of magnitude, and as the most-experienced person in the room by an order of magnitude.

** A few disclaimers

Footnotes to real sources have been added where possible, but there is bound to be some amount of Tim Making Things Up. Also, this document deals indiscriminately with country dancing from approximately 1750-1820 in the Highlands of Scotland, the Lowlands of Scotland, urban England, and colonial America. Please don't leave with the impression that dancing was the same at all times in all places; it's just that elaborating on regional and temporal variations is out of scope.

Additionally, I have no formal medical training. Suggestions below are based on things I and others do regularly, but if a movement or position causes you serious pain please don't do it, and if you have a pre-existing injury or condition please only attempt things that seem responsible.

* Position and Posture

Dancing is frequently defined as ``moving to music", but  there is much to be said for looking the part even when /not/ moving. A room full of people slouching looks disheveled; a room full of people standing like dancers looks like an Event.

Similarly, all movement is designed to come from someone in the position of a dancer and can look especially incongrous otherwise.

Finally, for those already in good shape, good dance position helps prevent minor pains and more serious injuries. (For those with an injury history or some other ailment, please do something responsible.)

** Standing

There is quite a bit of overlap between the position of a period country dancer, the position of a period soldier, and the position of a modern ballet dancer. All emphasize a straight back and open hips; the most significant distinction is the position of the feet and arms.

The key element is standing up straight, which does /not/ mean pulling your shoulders back and sticking out your belly.

Some people imagine putting headlights on their pelvis and then standing so that the headlights shine parallel to the ground, not down into it (it will feel like you're rotating your pelvis up to bring the beams of light up). Others think of ``zipping up" the stomach—pulling up on the front of the pelvis and tightening the butt muscles. Others speak of avoiding ``Donald Duck butt" or ``leading with the chest". Whatever the method, your vertebrae should end up stacked on top of each other, your shoulders should be above your hips, and the area below the belt should feel…ah...slightly exposed.

This established, it's then easy to have good turnout. Turnout comes not from the knees (twisting the knees will wreck them) but from the hips. Opening up the hips as above lets each leg rotate out in its entirety; your heels will naturally come to the center and your toes will naturally point more to the side. Having good turnout and ``being a flexible person" are mostly unrelated; achieving turnout is more about technique than having lengthened muscles.

The position of a standing dancer, then, is standing up straight, having good turnout, letting the heels touch each other and the feet form a 90° angle, and letting the arms rest loosely at one's sides (the elbows with a natural bend).

** Moving

The specifics of footwork will be addressed below, but effectively all propulsion should come from the toe and maintain turnout. When taking a step lead with the toe and let the toe strike the ground first. At sufficient speeds the heels may /never/ hit the ground.

* Traveling Steps
One of the biggest differences between period dancing and modern English country dancing is simply how one moves. In the period, nobody walked. The single biggest improvement reenactors could make to their dancing is by using a dance step to move around!

** In two or four
Most dancing is in reel time, which in the 18th century was either 2/2 or 6/8. Surprisingly, only the details change between the two: the general idea is the same in either meter. The below steps also apply to strathspeys (which are in 4/4[fn::Macdonald] and slower), but strathspeys are less likely to be found in the wild.

*** Skip-change-of-step (kemshóole[fn::Peacock, 91])
The core way of getting somewhere. I like to call it out as ``step-close-step-hop". To wit:

1. With your weight on your left leg, reach out with your right foot (toe pointed! Turnout maintained!) and step onto it.
2. Slide the left foot in behind the right foot (ideally with the left foot's instep touching the right foot's heel: third position) and transfer weight onto the left foot.
3.Reach out with your right foot again, as in step #1.
4. Hop forward on the right foot, /meanwhile/ pull the left leg through, ready for the /left/ foot to reach out.

The process then repeats with the sides switched. Each cycle (#1-4) occupies one bar of music.

Teaching it can be tricky. The key element of the step is handling momentum on step #4: pulling one leg through in a continuous motion and using its weight and your forward motion to effect a hop on the other foot. Therefore, doing it slowly doesn't really translate to doing it at speed.

Instead, I have dancers start by doing a elementary-school-style gallop in a circle—leading with the right foot and always bringing the left foot up behind it. Once everyone's galloping I have them switch to leading with the left foot.  Then I have them do eight gallops on the right followed by eight on the left, then four and four, then two and two and two and two. Alternating by two is equivalent to the desired dance step; all that's left is fine-tuning the footwork (pointed toes! Good turnout! Closing in third position!).
*** Peacock's variation
Francis Peacock suggests that one ``may introduce a very lively" variation by, effectively, galloping by four and four instead of by two and two. When dancing it does make a surprisingly big difference, both to the dancer and to the observers!
** In three (quicktime)
Shockingly, there are a number of period dances in three (almost always 9/8) and, as far as I know, zero explanations of the relevant footwork. The folk tradition has two candidates. Both are based on skip-change-of-step as explained above, but need to have six bits instead of four bits to work in the new meter. Choose your favorite; it doesn't really matter which one you do.

*** Skip-change-of-step, always leading with the right

1. #1 as above
2. #2 as above
3. #3 as above
4. #4 as above
5. Reach out with your left foot and step onto it.
6. Pull the right leg through /while/ hopping on the left foot, ready for #1 (again with the right!)

*** Skip-change-of-step, alternating
1. #1 as above (that is, as it would be in two)
2. #2 as above
3. #1 again as above
4. #2 again as above
5. #3 as above
6. #4 as above, ready to repeat with sides switched.

In other words, steps 1 and 2 are repeated before continuing on as normal.

I have only ever taught these by demonstrating, explaining the basics in words, and then playing 9/8 music for several minutes while letting people roam around the dance floor working it out on their own. There may be a better way of doing this, but that's for you to figure out.

* Setting Steps

Setting (also known as ``footing it") is where individual creativity can best shine. As far as I can tell there are no real rules to doing it right; one simply bops around to the allotted music while staying in roughly the same spot on the floor. Peacock lists quite a few options for setting and concludes with: ``I shall only add, that you have it in your power to change, divide, add to, or invert, the different steps described, in whatever way you think best adapted to the tune, or most pleasing to yourself"[fn::Peacock, 98].

Unless you're dancing the Scotch Reel, it is likely that you will only have occasion to set for two bars of music at a time. The below options can fill those two bars. There are more complex options—some that require more bars of music, and some that are just plain hard. I leave them all for another time.

** The cop-out
I call this as ``right-left-right <silence> left-right-left"

1. Step onto the right foot
2. Step onto the left foot
3. Step onto the right foot
4. Pause, with your left foot suspended in the air

Then repeat with the sides switched. For bonus points, try to land on your toes, point your toes, and generally look light on your feet.

** The pas de basque
This is a classier version of the cop-out.

1. Step onto the right foot
2. Bring the toe of the left foot next to the instep of the right foot, pushing down on the left foot to get the right foot a little off the ground (i.e., transferring weight)
3. Transfer weight back to the right foot, letting the left foot come off the ground (toes pointed!)
4. Pause, with your left foot in the air. For extra style points, add a /jeté/: straighten the left knee such that your left foot extends out over the ground diagonally to your front-left.

Then repeat with the sides switched.

** The back-step (minor kemkóssy[fn::Peacock, 92])
1. Put your right foot /behind/ your left one
2. Hop forward on your right foot as you swing your left leg out, ready to
3. Put your left foot behind your right one
4. Hop forward on the left foot, swinging the right foot around

Those four steps occupy two bars of music, so do /not/ repeat.

* Terminology

* Progression

* Common Figures

* Of the Music

* On Being Polite

* Graded Dances

* Works Cited

- [AD] A. D. Dancing Master. /Country-Dancing made Plain and Easy to Every Capacity/. London, 1764.
- [Macdonald] Macdonald, Timothy S. ``Strathspeys, Reels, and Strathspey Reels: Clarifying Dance Music in Lowland Scotland 1750-1833" Awaiting publication in /The Proceedings of the 2018 North Atlantic Fiddle Convention/, 2019.
- [Peacock] Peacock, Francis. /Sketches Relative to the History and Theory but more especially to the Practice of Dancing/. Aberdeen, 1805
